### ISSUE TITLE
Rendering trees with renderString()

### ISSUE THREAD

**Issue by chrisbuttery** [segmentio/deku#116]
Heyo, Looking into `renderString()` and rendering the `counter` [example component](https://github.com/segmentio/deku/blob/master/examples/counter/index.js) with koa.
Koa is rendering it as expected `Seconds Elapsed: 0`, but the component doesn’t actually count as it does when mounting with the `render()` method and compiling with browserify.

I’m assuming this is more of an implementation issue (because I'm just guessing here), than a problem with `renderString()`, right?

```js
var koa = require('koa');
var app = koa();
var port = process.env.PORT || 1337;

var deku = require('deku');
var tree = deku.tree;
var element = deku.element;
var renderString = deku.renderString;
var Counter = require('./lib/counter');

app.use(function *(){
  function doSomething() {
    console.log('I did something.');
  }

  var counter = tree(
    element(Counter, { onAnEmittedEventFromCounter: doSomething })
  );

  this.body = renderString(counter);
});

var server = app.listen(port, function() {
  console.log('Koa is listening to http://localhost:' + port);
});
```

**Comment by chrisbuttery** [comment]
Derp.
The [lifecycle methods](https://github.com/segmentio/deku/blob/master/docs/guides/components.md) `afterMount` and `afterUpdate` are not fired on the server.

**Comment by anthonyshort** [comment]
Yup, only `beforeMount` and `beforeRender` should be called
