### ISSUE TITLE
Publish on npm / npm module name

### ISSUE THREAD

**Issue by yoshuawuyts** [segmentio/deku#23]
Apparently `deku` isn't published to npm. If you want to use Deku with Browserify (see also #17)  it would be nice if `deku` itself was on npm. The name `deku` is taken already though. Would you be interested in publishing it to npm possibly under a new name?

Some names that are available on npm:
- `deku-ui`
- `segmentio-deku`
- `component-deku`

I also saw a (joking) suggestion to [change the name](https://github.com/segmentio/deku/issues/3#issuecomment-63205323), but I'm not sure if this is something you guys would want to do.
Thanks!

**Comment by anthonyshort** [comment]
Published as `deku` :)

**Comment by yoshuawuyts** [comment]
dope!
