### ISSUE TITLE
What is the difference between state and props?

### ISSUE THREAD

**Issue by tcoats** [segmentio/deku#27]
I'm really liking this so far. Very clean and simple. Everything is fairly understandable except I think state and props.

**What is the difference between state and props and when would I use one over the other?**

Looking at the examples I can see that props is being altered through scene.setProps. Is this the only way to manipulate props?

State and props seem to be individual per component. How do I pass information to any child components? Through props.children? What is props.children?

Also how does deku fit with ripple.js? Is it a successor?

And my last question, should I be using deku now? And what is your goal for deku?

**Comment by anthonyshort** [comment]
It's just about ready for a proper release, the main things left are just the docs, which would help with these sort of questions.

If you've ever used Facebook's React, the API is very similar. We're probably going to things differently as the library develops though.

`state` is for internal component data. Only the component can change this and it can't be access or changed from anywhere else. This is updated via `this.setState()`.

`props` is for external data. This is what is passed down from parent components. The only place to change props directly is on the scene. You can set the props of child components during the `render` hook.

```js
var Child = component({
  initialState: function(){
    return { 
      name: 'Tom'
    };
  },
  render: function(props, state){
    return dom('div', [
      props.name,
      state.name
    ])
  }
});

var Parent = component({
  render: function(props, state){
    return dom('div', [
      Child({ name: 'Jerry' }) // Compose another component inside, setting the props 
    ]);
  }
});

Parent.render(document.body);
```

**Comment by tcoats** [comment]
Brilliant, thank you.

I'm going to start using it. The `afterMount` and `beforeUnmount` look like the perfect way to integrate other plugins like leafletjs.

**Comment by anthonyshort** [comment]
Great! Let me know if you have any problems. Specifically let me know if the API feels awkward anywhere.
