### ISSUE TITLE
SVG support

### ISSUE THREAD

**Issue by tcoats** [segmentio/deku#30]
I believe svg elements require `document.createElementNS` instead of the usual `document.createElement`. Is this something deku would want to support?

Perhaps a domsvg method to supplement the dom method? Although ideally it would be invisible to the user and work with the existing dom method. d3 handles this duality somehow.

Here's an example:

```html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Test</title>
<script src="lib/deku.min.js"></script>
</head>
<body>
<!-- <svg height="100" width="100">
  <circle cx="50" cy="50" r="40" stroke="black" stroke-width="3" fill="red"></circle>
</svg> -->
<script>
component = deku.component;
dom = deku.dom;

var App = component({
  render: function(props, state) {
    dom('svg', { height: '100', width: '100' }, [
      dom('circle', {
        cx: '50',
        cy: '50',
        r: '40',
        stroke: 'black',
        'stroke-width': '3',
        fill: 'red'
      })
    ]);
  }
});
App.render(document.querySelector('body'));
</script>
</body>
</html>
```

**Comment by Raynos** [comment]
@anthonyshort 

Check out https://github.com/Matt-Esch/virtual-dom/blob/master/virtual-hyperscript/svg.js for the full nuances of virtual SVG.

Consider contributing and sharing ;)

**Comment by anthonyshort** [comment]
I knew this would come up eventually haha yeah I planned on adding support for it. Ultimately I'd like virtual-dom and other libs to just be using the same module. I only wrote the custom one for deku because the problem was pretty complex at the start.

I might check this out soon :)

**Comment by voronianski** [comment]
+1

**Comment by voronianski** [comment]
@anthonyshort I need `.svg` working in the project that I'm currently developing with deku. So I can take this feature and make a pull-request. Should deku proceed with custom virtual DOM or use something like https://github.com/Matt-Esch/virtual-dom?

**Comment by anthonyshort** [comment]
We'd want to make sure it still supports the JSX transform, so it should all just live inside the `element` function and we can figure out if it's SVG.

We just need to set the namespace on the elements themselves (https://developer.mozilla.org/en-US/docs/Web/SVG/Element). 

The renderer then needs to use `document.createElementNS` (https://developer.mozilla.org/en-US/docs/Web/API/Document/createElementNS) and `setAttributeNS`. 

Maybe the best option is to just have a list of elements/attributes that are for svg and let the renderer figure it out.

**Comment by voronianski** [comment]
@anthonyshort yeah, probably the same list of supported elements/attributes as in React will be enough:

- svg elements - https://facebook.github.io/react/docs/tags-and-attributes.html#svg-elements
- svg attributes - https://facebook.github.io/react/docs/tags-and-attributes.html#svg-attributes

**Comment by anthonyshort** [comment]
Oh nice! Yeah good call :)

**Comment by anthonyshort** [comment]
We could check the tagName here: https://github.com/segmentio/deku/blob/master/lib/render.js#L433 and check the attribute name here: https://github.com/segmentio/deku/blob/master/lib/render.js#L817

Using the list of supported elements/attributes is probably enough for now

**Comment by anthonyshort** [comment]
Basic support added thanks to @voronianski :dancer: :+1:
