### ISSUE TITLE
prop declaration/validation

### ISSUE THREAD

**Issue by anthonyshort** [segmentio/deku#31]
```js
var Button = component()
  .prop('onClick', { type: 'function', required: true })
  .prop('text');
```

If you send a property through that isn't declared, it will show a warning in the console in `dev` mode.

```
Warning: Undefined prop `text` set on component `Button`
Warning: Invalid type 'boolean' for prop `text` on component `Button`. Expected 'string'
```   

It could be a plugin too:

```js
Button.use(validation())
```

Alternative syntax for class-style:

```js
var Button = component({
  props: {
    'text': { type: 'string', required: true }
  }
});
```

**Comment by Raynos** [comment]
@anthonyshort

I would recommend you allow people to choose between `console.warn` and thrown exceptions.

**Comment by anthonyshort** [comment]
Something like `deku.development(true)` could work nicely for that.

**Comment by anthonyshort** [comment]
This is currently sitting in master. It'll go out with the 1.0 release.
