### ISSUE TITLE
How to query for current state?

### ISSUE THREAD

**Issue by tcoats** [segmentio/deku#32]
It looks like a component can't query for state but can save state against `this` instead. The below example is a number that increments every second. The function running from `setInterval` can't query for changed state, so can only use a variable previously saved against `this`.

Is there a better way to implement this example?

Additionally there is no way to invalidate state without passing a new variable to `setState`. I understand that render should only rely on state so that makes sense, however in this example I'm having to use another variable to copy the state.

Taken to the extreme it might be easier to always make a copy of props and state to `this` on every update, however I suspect there is a good reason why this isn't already available in the API.

```html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Test</title>
<script src="lib/deku.js"></script>
</head>
<body>
<script>
var component = deku.component;
var dom = deku.dom;

Seconds = component({
  initialState: function(props) {
    this.value = props.value;
    return { value: this.value };
  },
  tick: function() {
    this.value++;
    this.setState({ value: this.value });
  },
  afterMount: function(el, props, state) {
    this.interval = setInterval(this.tick.bind(this), 1000);
  },
  beforeUnmount: function() {
    if (this.interval != null) {
      clearInterval(this.interval);
    }
  },
  render: function(props, state) {
    return dom('div', state.value.toString());
  }
});

Seconds.render(document.querySelector('body'), { value: 0 });
</script>
</body>
</html>
```

**Comment by anthonyshort** [comment]
Deku doesn't expose the state like that so that components are basically just hooks that get called. This is done to make testing easier since you're not relying on any state you can just pass things in and check the result. 

For this use-case, I'd just use a function and avoid storing state:

```js
Seconds = component({
  initialState: function(props) {
    return { value:  props.initialValue };
  },
  tick: function(count) {
    var self = this;
    return function(){
       self.setState({ value: count += 1 });
    };
  },
  afterMount: function(el, props, state) {
    this.interval = setInterval(this.tick(props.initialValue), 1000);
  },
  beforeUnmount: function() {
      clearInterval(this.interval);
  },
  render: function(props, state) {
    return dom('div', state.value.toString());
  }
});
```

**Comment by tcoats** [comment]
Excellent, thank you.

I use CoffeeScript which has a similar concept, cheers.
