### ISSUE TITLE
Event Delegation

### ISSUE THREAD

**Issue by spenceralger** [segmentio/deku#35]
Perhaps I'm just used to this working because I've spent too much time around `ng-click` and `$.delegate`, but shouldn't events bubble up from children to their parents?

Currently, I'm not seeing this behavior. [Repro](http://plnkr.co/edit/HFKKAVcndtxfgNv4pA1B?p=preview)

1. Active links are green, inactive are red
1. clicking the link text, the link does not become active
1. click the padding of the `<li>`
1. since the handler is assigned to it, the `<li>` turns active

Is there a way to make this work without assigning click handlers to every element within the click zone?

**Comment by anthonyshort** [comment]
Looks like I'm using the wrong target. It does delegate, and that's the way it should work :p

I'll use this to write up a test and get it fixed up tomorrow! If you want to check it out, it's in /lib/renderer/html/interactions.js that thing handles all of the events on the scene. Super simple.

**Comment by spenceralger** [comment]
Yeah, was definitely looking there to see what was going on, and it looks like the problem has to do with the keypath module... Not even sure what I'm saying but that is where the code seems to behave differently.

**Comment by spenceralger** [comment]
If I wasn't in the middle of a 48 hour hackathon I would spend more time diagnosing. For now we're just relying on routing for scenarios like this. LOVING deku so far!!

**Comment by anthonyshort** [comment]
Looks like it's the event.target. We need to find the delegate target. Simple fix :) glad you're liking it, it's getting close to a proper release.

**Comment by spenceralger** [comment]
Oh, duh. Super simple fix. How do I build/test? I'm getting missing module
errors after running `make` and trying to run the dist/deku.js file

**Comment by anthonyshort** [comment]
Just pushed up 0.0.18 that fixes it :) There was an issue with one of the deps, but that's solved now. Thanks!
