### ISSUE TITLE
TodoMVC Example

### ISSUE THREAD

**Issue by anthonyshort** [segmentio/deku#39]
Ya know, to be cool and stuff

**Comment by joshrtay** [comment]
a performance benchmark vs react would also be cool

**Comment by yoshuawuyts** [comment]
@joshrtay that might actually best be a separate issue, if there is none already.

**Comment by joshrtay** [comment]
i was thinking you could use the TodoMVC example as the benchmark

**Comment by yoshuawuyts** [comment]
Oh right, I see. That would indeed be neat ^_^
