### ISSUE TITLE
Moving diffing to virtual DOM

### ISSUE THREAD

**Issue by anthonyshort** [segmentio/deku#42]
The diffing of the trees should be moved to the virtual dom module, which would return an array of changes to apply the to the element in the HTMLRenderer. We can't use another diffing module because of the unique way we're handling components.

**Comment by yoshuawuyts** [comment]
I want to give this a shot this weekend, it's bugging me that I can't use [`virtual-html`](https://github.com/azer/virtual-html) with `deku`. Not sure how far I'll get, but I'll definitely be reporting my findings back here.

**Comment by yoshuawuyts** [comment]
I want to give this a shot this weekend, it's bugging me that I can't use [`virtual-html`](https://github.com/azer/virtual-html) with `deku`. Not sure how far I'll get, but I'll definitely be reporting my findings back here.

**Comment by anthonyshort** [comment]
I would like to, but it seems like it might not work because they don't have the same idea of components. They have widgets, but I'm not sure they work the same way. I've mainly not used it because it's pretty hard to figure out how the widgets work in virtual-dom

**Comment by anthonyshort** [comment]
This was mostly just to separate the logic between the diffing and the patching. It's all in ./renderer/html/diff.js at the moment. The diff should take a virtualize node and return an array of changes instead, then process those using the renderer to update the element. 

It'll just make it easier to optimize both of them.

**Comment by yoshuawuyts** [comment]
Cool, I'll look into pulling in just the diffing algorithm this weekend then ^^

**Comment by yoshuawuyts** [comment]
Didn't get around to it this weekend; considering https://github.com/segmentio/deku/pull/57 is marshals in some large changes I figured it's be best to wait until that is merged.

**Comment by anthonyshort** [comment]
It should be much easier now anyway after this commit: https://github.com/segmentio/deku/commit/1e3216508698a087aebed30c43fbaa1ec73e0e81

I'm also not entirely sure it's needed now though. The diff is so simple anyway.
