### ISSUE TITLE
Context

### ISSUE THREAD

**Issue by anthonyshort** [segmentio/deku#43]
We could potentially send through a `view` or `context` object to the component hooks that holds the props, state, element, previous state, channels etc. on it. It could also have a `.setState` method.

This will pull all state off the component and allow the hooks to be easier to setup. This should be it's own class that we expose so people can easily create them for testing components.

**Comment by yoshuawuyts** [comment]
For reference, here's the example syntax as outlined in https://github.com/segmentio/deku/issues/51:
```js
button = component()
  .use(plugin())
  .prop('text', { type: 'text' })

button.render(function(context){
  let {text} = context.props;
  return <div>{text}</div>;
});

button.afterMount(function(context){
  context = context.setState({ text: 'mounted' });
  return context;
});
```
