### ISSUE TITLE
Replace event handlers on re-render?

### ISSUE THREAD

**Issue by lancejpollard** [segmentio/deku#47]
So if you have this:

```js
var Page = component(function(props, state){
  var error = state.error;
  var self = this;

  function createError() {
    self.setState({ error: 'An error at ' + new Date });
  }

  function logError() {
    console.log(error);
  }
  
  return dom('div', [
    div('div.foo', { onClick: createError }, 'Create error')
    dom('div.log', { onClick: logError }, 'Log error')
  ]);
});
```

1. first time around: `error == null`
2. second time after you click `Create error`: `error == 'An error at (Date)'`

However, that `logError` function doesn't seem to be replaced between set states. This means, any time you click `Log error`, it will print `null`.

So basically it seems Deku just needs to replace event handlers each time. Thoughts?

**Comment by anthonyshort** [comment]
It should be replacing all the handlers on each render already. Ill write a test for it and see it fails.

**Comment by anthonyshort** [comment]
Added this test for it and it's passing: https://github.com/segmentio/deku/commit/a62f84afcd61dae3143fa6f8946c54c6daeb0506

Maybe it's something else?

**Comment by lancejpollard** [comment]
Ah interesting. Yeah maybe I need to come back at it from a new angle. Maybe it was chrome debugging that was making it seem like it? Not sure

**Comment by lancejpollard** [comment]
Hmm, will dig into it when I get back, maybe it could be when that component is nested? Doesn't seem like it, hmm

**Comment by anthonyshort** [comment]
I'm thinking it might be something to do with the component not updating because it thinks the state/props is the same. Another reason why we should use immutable.js internally :) It'll make all this way easier. I'll hack on it on the weekend.

**Comment by lancejpollard** [comment]
Mmm, yeah super weird. I think it may have something to do with how some components are wired up, gonna try more stuff, closing for now.

**Comment by lancejpollard** [comment]
Another demo of this is:

```js
var Page = component(function(props, state){
  var setState = this.setState;
  var error = state.error;

  // log error and change state.
  function log() {
    console.log(error);
    setState({ error: 'Error at ' + new Date });
  }

  return dom('div', [
    Button({
      label: 'Log it',
      onClick: log
    })
  ]);
});

var Button = component(function(props){
  var onClick = props.onClick;
  var label = props.label;
  return dom('button', { onClick: onClick }, [ label ]);
});
```

In there, the props in `Button({ label: 'Log it', onClick: log })` never technically change between re-renders. BUT, the context of that `log` function _does_ change between renders. This seems to mean, if props include a function, they should always be considered dirty?

Basically just needs some way to diff functions.

**Comment by lancejpollard** [comment]
Weird, it looks like those scoped functions are not equal, so it should be like this:

```js
buttonState1.props.log === buttonState2.props.log
// false
```


```js
(function(){
  var fns = [];

  render({ text: 'first' });
  render({ text: 'second' });
  render({ text: 'third' });
  print();

  function render(props, state) {
    function fn() {
      return props.text;
    }

    fns.push(fn);
  }

  function print() {
    console.log('  The nested functions are all not equal to each other.');
    console.log()
    fns.forEach(function(fn, i){
      if (!i) return;
      var equal = fns[i] === fns[i - 1];
      console.log('  ' + equal);
    });
    console.log('')
    console.log();
  }
})()
```

**Comment by lancejpollard** [comment]
Oh also wanted to mention, this can be fixed by passing in a prop that's always unique, such as:

```js
  return dom('div', [
    Button({
      label: 'Log it',
      onClick: log,
      hack: new Date
    })
  ]);
```

**Comment by lancejpollard** [comment]
Looks like it's a bug in `require('equals')`.

**Comment by lancejpollard** [comment]
Whoa.

In Node it's different:

```js
(function(){
  var deepEqual = require('deep-equal');
  var equal = require('equals');
  var fns = [];

  render({ text: 'first' });
  render({ text: 'second' });
  render({ text: 'third' });
  print();

  function render(props, state) {
    function fn() {
      return props.text;
    }

    fns.push(fn);
  }

  function print() {
    console.log('  The nested functions are all not equal to each other.');
    console.log()
    fns.forEach(function(fn, i){
      if (!i) return;
      var a = fn[i];
      var b = fn[i - 1];
      console.log('  a === b', a === b);
      console.log('  substack/node-deep-equal (strict): ' + deepEqual(a, b, { strict: true }));
      console.log('  substack/node-deep-equal: ' + deepEqual(a, b));
      console.log('  jkroso/equals: ' + equal(a, b));
    });
    console.log();
  }
})()
```

```

  a === b true
  substack/node-deep-equal (strict): true
  substack/node-deep-equal: true
  jkroso/equals: true
  a === b true
  substack/node-deep-equal (strict): true
  substack/node-deep-equal: true
  jkroso/equals: true

```

In the browser it's:

```
  The nested functions are all not equal to each other.

  a === b false
  a === b false

```

Don't know about the other ones in the browser.
