### ISSUE TITLE
Make html escaping the default

### ISSUE THREAD

**Issue by lancejpollard** [segmentio/deku#55]
It's super easy to forget to escape stuff to prevent XSS attacks. For example, if you allow users to enter some input into a textarea, and then you show that content somewhere in your app outside the textarea (even in multiple places), it's very easy to not realize it needs to be escaped.

So it would be a lot safer if it was the default :)

Basically it takes just using https://github.com/component/escape-html to escape any text node.

```js
text = escape(text);
```

This will prevent a user from, for example, entering this into a text input:

```
hello <img src=x onerror="alert('i gonna steal yo cookies')">
```

**Comment by yoshuawuyts** [comment]
[OWASP on Escaping All User Supplied Input](https://www.owasp.org/index.php/SQL_Injection_Prevention_Cheat_Sheet#Defense_Option_3:_Escaping_All_User_Supplied_Input):
> (...) this methodology is frail (...) and we cannot guarantee it will prevent all SQL Injection in all situations. This technique should only be used, with caution (...)

Also the [first link on Google when searching for "escape all input"](http://lukeplant.me.uk/blog/posts/why-escape-on-input-is-a-bad-idea/):
> The right way to handle issues with untrusted data is: Filter on input, escape on output

It appears that opinions are not unanimously in favor of escaping all input. Making this the default might not make sense for all users. Maybe this is a good use case for a [plugin](https://github.com/segmentio/deku/wiki/Component-API#componentuseplugin-objectfunction--self)?

**Comment by lancejpollard** [comment]
Awesome links, yeah a plugin would be nice for this, makes sense.

**Comment by anthonyshort** [comment]
A plugin that just escapes the value on `beforeUpdate` would probably work.

```
component()
  .use(escape('myField'))
```

**Comment by anthonyshort** [comment]
Although I kinda hate the idea of having to build plugins for something that is so generic... it should just be composed.

```
Thing.prototype.beforeUpdate = compose(escape, doStuff, doMoreThings);
```

**Comment by lancejpollard** [comment]
Mmm, React has this as the default:

> React escapes all the strings you are displaying in order to prevent a wide range of XSS attacks by default.

http://facebook.github.io/react/docs/jsx-gotchas.html#html-entities

I think we should do the same to be safe. @yoshuawuyts after thinking more about those links, they are talking about problems with escaping on input, which makes sense. But still, this is a potential serious security threat that should be avoided without having to walk on eggshells.

Rails does this by default too: http://yehudakatz.com/2010/02/01/safebuffers-and-rails-3-0/

It is far too easy to forget to include escaping. It's like "who cares" for small apps, but for large-scale production apps, one slip and you're toast. Someone can add `<img src=x onerror="post_to_my_server(document.cookies)">` and now they can login as admin and they have full access to everything.

We should do this by default.

The only reason we should not do this by default is theoretically for performance. But escaping isn't going to be a performance problem for a long long time. There are many other things to optimize first, and I don't think we'll ever run into this causing a performance problem.

**Comment by lancejpollard** [comment]
hmm:

https://www.owasp.org/index.php/DOM_based_XSS_Prevention_Cheat_Sheet

after testing it out, it looks like `document.createTextNode('<img src=x onerror="post_to_my_server(document.cookies)">');` and `el.data = '<img src=x onerror="post_to_my_server(document.cookies)">';` both escape by default, or at least you can't XSS attack through them.

So then it comes down to `innerHTML`. The case where this was a problem was we had a nested component where we passed in `<AComponent>{ content }</AComponent>`, which then internally (a few layers down) did `<div innerHTML={ markdown(content) }></div>`. How to prevent it from happening there? Seems much more involved.

**Comment by yoshuawuyts** [comment]
@lancejpollard Hah, after thinking about it a little more I agree. Being safe is better than being correct. It appears [`virtual-dom`](https://github.com/alexmingoia/virtual-dom-stringify/blob/3c6f6111ac6d1707e93bb3bf323783609a4d8937/lib/stringify.js#L92-L99) doesn't warn people about using `innerHTML` either. Not sure what the correct solution is here; having a few hoops to jump through makes it less of an accidental slip up I guess. React uses:
```js
react.dom('div', {dangerouslySetInnerHTML: {__html: '<my-elements></my-elements}})
```
which is no fun to write, hence reducing the chance of abuse. Maybe `deku` would want some obstacles too? This feels like something the `mercury` guys have also had to deal with also, might be worth checking up with them.
