### ISSUE TITLE
Set default props

### ISSUE THREAD

**Issue by daryl** [segmentio/deku#71]
What are your thoughts on implementing something like `initialProps`?

```js
initialProps() {
  return {
    ...
  };
}

```

**Comment by anthonyshort** [comment]
Yeah I think we could add that. I haven't had the need for it just yet, but I can see why it's useful :)

**Comment by anthonyshort** [comment]
Going to add this in 0.1.0 #70

**Comment by anthonyshort** [comment]
In the next version you'll be able to specify default props:

```
var Button = {
  defaultProps: {
    color: 'red'
  }
}
```

These are static and shared across all component instances.
