### ISSUE TITLE
`renderString` isn't firing `beforeMount`

### ISSUE THREAD

**Issue by daryl** [segmentio/deku#73]
[It says here](https://github.com/segmentio/deku/wiki/Component-API#componentbeforemountprops-state) that `beforeMount` is fired when `renderString` is called. It's not working for me.

I should probably mention I'm using `0.0.28`, so it may already be fixed.

**Comment by lancejpollard** [comment]
Ah yeah @anthonyshort I removed this because, originally, `beforeMount` was only firing on the root element (not on any nested element), so seemed like it wasn't technically there.

**Comment by anthonyshort** [comment]
Yeah it should be firing once for every component that gets rendered.

**Comment by anthonyshort** [comment]
This will be fixed in v0.1.0 with #70. Should get this out today.
