### ISSUE TITLE
require setState instead of passing it through context

### ISSUE THREAD

**Issue by queckezz** [segmentio/deku#80]
Hey, once again, awesome job you guys have done here with deku! Really impressed.

Just a suggestion that has come to my mind. What do you guys think of requiring `setState` as a simple utility function instead of passing it to the component's context? I think the `component()` constructor is overloaded with 4 arguments. This would make the function `setState()` more transparent.

The function would set the state given a `component` and the new state. Like it is now, except not partially applied.

Basically just switching
```js
export function afterUpdate (component, prevProps, prevState, setState) {
  let {props, state} = component
  if (!state.clicked) {
    setState({ clicked: true })
  }
}
```

to

```js
import { setState } from 'deku';

export function afterUpdate (component, prevProps, prevState) {
  let {props, state} = component
  if (!state.clicked) {
    setState(component, { clicked: true })
  }
}
```

It seems like this is not possible though, since the entire `entity` is needed and not just `entity.component`.

**Comment by anthonyshort** [comment]
Yeah that's a neat idea. We could figure it out just using the id actually. 

The only benefit we get from passing it in is that we can limit when they can update state to push towards better practices. If it's available as just an import, it could be unpredictable when/where state is changing.

**Comment by anthonyshort** [comment]
Come to think of it, requiring it like this requires the renderer to be a global singleton (like React) which we don't want to do so I'm going to close this for now. But it's an interesting API though.
