### ISSUE TITLE
Unable to access sources after the component is re-rendered

### ISSUE THREAD

**Issue by stevenmiller888** [segmentio/deku#87]
@lancejpollard 

Here's an example demonstrating this:

```
var app = tree(<App/>);
app.set('hello', 'world');
render(app, document.body);
```

You *can* access the `'hello' ` source from within the `App` component the first time `render` is called. However, any time `render` is called after that, you can no longer access the `'hello' ` source from within the `App` component.

**Comment by lancejpollard** [comment]
This is fixed now with https://github.com/segmentio/deku/pull/94 :)
