### ISSUE TITLE
Parent component setState inside passed handler to child

### ISSUE THREAD

**Issue by voronianski** [segmentio/deku#88]
The lack of docs leads me to investigation of proper way to pass function handlers from container component to pure components. 

## My example

I have a higher-order container element which handles state and passes necessary props to "pure" state-less components:

```javascript
/** @jsx deku.dom */

import deku from 'deku';

let Button = {
    handleClick(e, component) {
        e.preventDefault();

        let { playing, onToggle } = component.props;

       // do smth internally..
       // but I cannot pass setState from parent here..
       onTogglePlay && onTogglePlay(e, component);
    }, 

    render(component) {
        const { props } = component.;

        return (
            <button onClick={this.handleClick}>
                {props.playing ? 'Pause' : 'Play'}
            </button>
        );
    }
};

let Container = {
    initialState() {
        return {
            playing: false
        };
    },

    handleClick() {
         // I need to set `state` of Container here..
    },

    render(component) {
        let { state } = component;
        return (
            <div>
                <div>Some widget content</div>
                <Button playing={state.playing} onToggle={this.handleClick} />
            </div>
        );
    }
};

let app = deku.scene(
     <Container someProp="someData" />
);

deku.render(app, document.getElementById('app'));
```

As you see the problem is that I cannot take `setState` function from container inside passed handler.

I saw something similar in this example - https://github.com/segmentio/deku/blob/master/examples/todo/index.js#L18 Does it mean I need to use `app.set` with source on pure components?

**Comment by chrisbuttery** [comment]
Hi @voronianski, You just needed to move your handlers into the render method.

```
import { tree, render, element } from 'deku';

import deku from 'deku';

let Button = {
  render(component) {
    const { props } = component;

    function handleClick(e, component) {
      e.preventDefault();
      let { onToggle } = component.props;
      onToggle();
    }

    return (
      <button onClick={handleClick}>
        {props.playing ? 'Pause' : 'Play'}
      </button>
    );
  }
};

let Container = {
  initialState() {
    return {
      playing: false
    };
  },

  render(component, setState) {
    let { state } = component;

    function handleClick() {
      setState({
        playing: !state.playing
      })
    }

    return (
      <div>
        <div>Some widget content</div>
        <Button playing={state.playing} onToggle={ handleClick} />
      </div>
    );
  }
};

let app = tree(
  <Container someProp="someData" />
);

render(app, document.body);
```

**Comment by voronianski** [comment]
@chrisbuttery thanks, that should solve the issue. I just thought that creating handlers on every render isn't good idea.

**Comment by anthonyshort** [comment]
You also get `setState` passed in as the third param to handlers. But generally I just do what @chrisbuttery showed you.

**Comment by voronianski** [comment]
@anthonyshort alright I'll follow this pattern. Anyway it will great to have some input on `app.set` API as well.

**Comment by anthonyshort** [comment]
I'm spending most of tomorrow writing up some documentation so it should make more sense. But the `app.set` is a way to load data side-ways into the tree rather than needing to pass it down. It's for external data, like communicating with the your JSON API on the server. We're using it for:

* Routing - since a router is just an external data source
* Getting the logged in user 
* Communicating with our JSON API

I guess it's sort of like React's `context` object, but you can't modify it as you go down the tree.
