### ISSUE TITLE
Input tabbing

### ISSUE THREAD

**Issue by daryl** [segmentio/deku#89]
I noticed something earlier, when two inputs are next to each other, tabbing to the next wasn't natural.

Here's a [RequireBin](http://requirebin.com/?gist=e88cb8b2f8f6ab31b8ff) that emulates what I mean. Type in the left one, then try to tab to the other.

**Comment by anthonyshort** [comment]
Looks like we're losing the focus during the diff. The diffing is triggered the change event fires on tab out. I'll use that demo to make a test and see if we can fix it up.

We'll probably just need to do a check here: https://github.com/segmentio/deku/blob/master/lib/render.js#L708 for the `document.activeElement` and set it again after the change.

**Comment by anthonyshort** [comment]
I'm having trouble replicating it outside of the RequireBin example. Do you have any other examples of it busting?

**Comment by anthonyshort** [comment]
I just bumped deku in that bin to 0.2.15 and it worked fine :)

**Comment by daryl** [comment]
Oh, my bad. I hadn't updated Deku in a while, I was running `0.2.3`.
