### ISSUE TITLE
Deku & Components

### ISSUE THREAD

**Issue by metagen** [segmentio/deku#95]
I was thinking about web components, and I had a small thought..

Application logic vs Component logic

Components should manage user interaction, clicks, drags, visual reaction.
Applications know not of clicks, they have two functions...

1) Deal data: manage state, set authentication headers, model logic and transforms n' stuff.
2) page navigation & component lifecycles & compositing views

Scatter not thine top level into thine bottom level!

Manage not thine pristine components as you would HTML with jQuery!

Thoughts on how this applies to Deku?

**Comment by anthonyshort** [comment]
In Deku, components only care about themselves. They can only update their own state. Everything else is passed in, it's immutable, it's the environment the component lives in that it has no control of. This includes, but isn't limited to:

- the router, navigation
- page structure
- data sources
- 'global' concerns, like anything dealing with the document or window, like focus management.

Passing state down through components allows for props to be relative to the state of components that are parents or owners of the current component.

Application logic and state should live outside of the component and the tree, and update the state of the world which is the `tree` in deku.
