### ISSUE TITLE
Browser Support

### ISSUE THREAD

**Issue by rockymadden** [segmentio/deku#97]
First, fantastic library and approaches. Second, with the mention of `doesn't support legacy browsers` in the readme and SauceLabs stating many browsers are failing, is there a general ballpark of what browsers are going to be attempted to be supported in ~v1?

**Comment by anthonyshort** [comment]
Sorry, I just noticed CI was busted. 

We're supporting the latest 2 versions of the major browsers: IE10-11, Safari 7-8, Mobile Safari 8.0-8.2, FF/Chrome the latest 2 versions. Realistically, the only ones that will have trouble with it will be IE <10 because of the weird DOM support.

**Comment by rockymadden** [comment]
No worries, and thank you for the clarity on the browser support; exactly what I was looking for. Again, thank you very much for all your hard work. I'll be moving over projects soon!
