### ISSUE TITLE
Async data

### ISSUE THREAD

**Issue by boopathi** [segmentio/deku#99]
How to render Async data ?

The [blog post](https://segment.com/blog/deku-our-functional-alternative-to-react/) says - tree will manage loading data. What are plugins ?

There are multiple patterns, using [Observables](https://github.com/facebook/react/issues/3398), [Asynchronous actions](https://github.com/acdlite/flummox/blob/master/docs/docs/api/actions.md#asynchronous-actions) as in case of [flummox](https://github.com/acdlite/flummox) - a flux implementation and many others.

**Comment by boopathi** [comment]
Looks like some work has already been done in this context - https://github.com/segmentio/deku/pull/93

**Comment by anthonyshort** [comment]
You can set data on the tree https://github.com/segmentio/deku#external-data-and-communication and access it from components.

You can also load the data in `afterMount`

```js
function afterMount(component, el, setState) {
  api.getStuff(function(data){
    setState({ myStuff: data })
  })
}
```
